# .github/workflows/security-scan.yml

name: Build, SBOM and Security Scan

on:
  push:
    branches: [ "master", "develop" ]
  pull_request:
    branches: [ "master", "develop" ]
  workflow_dispatch:

jobs:
  build-and-scan:
    name: Build, Generate SBOM & Scan
    runs-on: ubuntu-latest

    steps:
      # 1. Adım: Kodu indir (v3 -> v4 olarak güncellendi)
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Adım: Node.js ortamını kur
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      # 3. Adım: Build işlemi
      - name: Install Dependencies
        run: npm install
      - name: Build Application
        run: npm run build
      
      # 4. Adım: Syft ile SBOM oluştur
      - name: Generate SBOM
        uses: anchore/sbom-action@v0
        with:
          format: 'spdx-json'
          output-file: 'sbom.spdx.json'

      # 5. Adım: Artifact'i kaydet (v3 -> v4 OLARAK GÜNCELLENDİ - HATANIN KAYNAĞI)
      - name: Upload SBOM Artifact
        uses: actions/upload-artifact@v4
        with:
          name: sbom-report
          path: sbom.spdx.json

      # 6. Adım: Semgrep CI aracını çalıştır
      - name: Run Semgrep CI
        uses: semgrep/semgrep-action@v1
        with:
          format: sarif
          output: semgrep.sarif
          
      # 7. Adım: Semgrep sonuçlarını GitHub'a yükle
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: semgrep.sarif
        if: always()
