# .github/workflows/security-scan.yml

name: Build, SBOM and Security Scan

# ÖNEMLİ NOT: Bu pipeline'ın doğru çalışması için reponuzda 'package-lock.json' dosyası bulunmalıdır!
# Eğer yoksa, local'de 'npm install' çalıştırıp oluşan dosyayı reponuza commit'leyin.

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]
  workflow_dispatch:

jobs:
  build-and-scan:
    name: Build, Generate SBOM & Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install Dependencies
        run: npm install

      - name: Build Application
        run: npm run build
      
      - name: Generate SBOM
        uses: anchore/sbom-action@v0
        with:
          dir: "."
          format: "spdx-json"
      
      - name: Run OWASP Dependency-Check
        uses: dependency-check/Dependency-Check_Action@main
        with:
          project: 'juice-shop'
          path: '.'
          format: 'SARIF'
          scan-args: "--disableYarnAudit --disableNodeAudit"

      # upload-sarif versiyonu v2 -> v3 olarak güncellendi
      - name: Upload Dependency-Check SARIF
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'dependency-check-report.sarif'
      
      - name: Run Semgrep CI
        uses: semgrep/semgrep-action@v1
        with:
          format: sarif
          output: semgrep.sarif
          
      # upload-sarif versiyonu v2 -> v3 olarak güncellendi
      - name: Upload Semgrep SARIF file
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: semgrep.sarif
        if: always()
