name: Secret and SAST Scan

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]
  workflow_dispatch:

jobs:
  scan:
    name: Scan for Secrets & SAST
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # --- KALDIRILAN ADIMLAR ---
      # - name: Set up Docker Buildx
      # - name: Build Docker image

      - name: Run Gitleaks to find secrets
        uses: gitleaks/gitleaks-action@v2
        continue-on-error: true
        with:
          report_format: sarif
          report_path: gitleaks.sarif

      - name: Run Semgrep CI
        uses: semgrep/semgrep-action@v1
        continue-on-error: true
        with:
          format: sarif
          output: semgrep.sarif
      
      - name: List files in workspace
        run: ls -R
        if: always()

      - name: Upload Gitleaks SARIF
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: gitleaks.sarif
          
      - name: Upload Semgrep SARIF file
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: semgrep.sarif
