name: Build, Secret and SAST Scan

on:
  push:
    branches: [ "master", "develop" ]
  pull_request:
    branches: [ "master", "develop" ]
  workflow_dispatch:

jobs:
  build-and-scan:
    name: Build, Scan for Secrets & SAST
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        # Gitleaks'in tüm geçmişi tarayabilmesi için 'fetch-depth: 0' gereklidir.
        with:
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          load: true
          tags: juice-shop-ci:latest

      - name: Run Gitleaks to find secrets
        uses: gitleaks/gitleaks-action@v2
        with:
          # Tarama sonuçlarını SARIF formatında oluştur
          report_format: sarif
          # Oluşturulacak rapor dosyasının adı
          report_path: gitleaks.sarif

      - name: Upload Gitleaks SARIF
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: gitleaks.sarif
          
      - name: Run Semgrep CI
        uses: semgrep/semgrep-action@v1
        with:
          format: sarif
          output: semgrep.sarif
          
      - name: Upload Semgrep SARIF file
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: semgrep.sarif
        if: always()
